### ISSUE TITLE
DOF removal for Links Awakening

### ISSUE THREAD

**Issue by AlexS2412** [masagrator/NXGraphicsPatches#11]
**Full game title**
The Legend Of Zelda: Links Awakening 
**Describe what you want to modify**
Removal of the DOF effect as it heavily impacts the game experience and generally looks bad in most overworld locations. here is an example. 
![2019091913451400-9129043EF2AAD7F1157CF852BACB8F7D](https://user-images.githubusercontent.com/14182708/65267888-f6873c00-dae3-11e9-9d75-810f29dd268d.jpg)
 from what i can tell it can most likely be turned off as it seems to be in any indoors location as seen here. 

![2019091909505500-9129043EF2AAD7F1157CF852BACB8F7D](https://user-images.githubusercontent.com/14182708/65267912-01da6780-dae4-11e9-865e-c9b1c15e7b61.jpg)

**Additional context**
if any other help can be provided in an attempt to fix this let me know. here are a few other examples of the heavy DOF causing issues. 
![2019091913452900-9129043EF2AAD7F1157CF852BACB8F7D](https://user-images.githubusercontent.com/14182708/65268080-60074a80-dae4-11e9-81dd-023b4e076857.jpg)

![2019091909534000-9129043EF2AAD7F1157CF852BACB8F7D](https://user-images.githubusercontent.com/14182708/65268099-6dbcd000-dae4-11e9-82c5-7b885463549f.jpg)

**Comment by AlexS2412** [comment]
someone made a fix now!
https://yuzu-emu.org/mods/ZLA_Noblur_Mod.zip

**Comment by AlexS2412** [comment]
actually it seems to only work on emulator.

**Comment by masagrator** [comment]
Here is the final mod
https://gamebanana.com/effects/download/6321
