### ISSUE TITLE
Digimon Story Cyber Sleuth: Complete Edition

### ISSUE THREAD

**Issue by rushtothesun** [masagrator/NXGraphicsPatches#12]
**Full game title**
Digimon Story Cyber Sleuth: Complete Edition

**Describe what you want to modify**
Achieve 60fps in handheld mode

**Describe many informations about this topic**
The game usually runs at 60fps when in the overworld, but when you get into a dungeon area it feels like there's an fps lock or something of the sort going on. There's little difference between no overclock and max overclock in these areas.

**Comment by masagrator** [comment]
Can you share save where I can get to dungeon instantly?

**Comment by rushtothesun** [comment]
https://gofile.io/?c=Mb3QUU

Go straight to load into the area.

**Comment by masagrator** [comment]
Game is not locking anything. It uses double buffer and jumps between 30 and 60 FPS. You can see that when choosing new game. It's 30 FPS, but if you will use OC, it will jump to 60 FPS. 
Dungeons looks like they are the worst optimized areas in game, so I can't help with that.
