### ISSUE TITLE
Luigi's Mansion 3

### ISSUE THREAD

**Issue by MysticExile** [masagrator/NXGraphicsPatches#14]
Luigi's Mansion 3 [0100DCA0064A6000]

Please look into the possibility of a 60FPS mod. Thank you in advance!

Docked 1080p
Handheld 720p
No Dynamic resolution

**Comment by masagrator** [comment]
60 FPS is now unlocked with proper speed. After some tests it will be released or if it's not meeting requirements, it will be uploaded to experimental branch.

**Comment by masagrator** [comment]
https://gbatemp.net/threads/luigis-mansion-3-60fps-mod.557992/
