### ISSUE TITLE
The Stretchers - 60FPS

### ISSUE THREAD

**Issue by stranno** [masagrator/NXGraphicsPatches#15]
**Full game title**
The Stretchers

**Describe what you want to modify**
Locked at 30FPS. I would want a 60FPS patch.

**Describe many informations about this topic**
Unreal Engine game, 4 i guess (tho it looks quite sharp for an Unreal Engine 4 game on Switch, dunno).

**Additional context**
Since it is an unreal engine maybe it could be modded through the config file, but i havent checked it.

**Comment by masagrator** [comment]
https://gbatemp.net/threads/the-stretchers-60-fps-mod.553073/
