### ISSUE TITLE
Senran Kagura: Peach Ball 60fps Mod

### ISSUE THREAD

**Issue by Watkinsjo2** [masagrator/NXGraphicsPatches#16]
**Full game title**
Senran Kagura: Peach Ball (JPN)

**Describe what you want to modify**
Boost framerate to 60fps

**Describe many informations about this topic**
Framerate is 30fps during gameplay but some segments like loading appear to run at 60fps

**Additional context**
I'm not sure if the codes are version-specific, but I own the Japanese release if that matters.

**Comment by masagrator** [comment]
Could you upload japanese version of exefs? I have only access to West version and I made mod for it. 

https://gbatemp.net/threads/senran-kagura-peach-ball-60-fps.553086/

**Comment by Watkinsjo2** [comment]
Here's a link to the freshly extracted exefs. I wasn't sure if I needed to do anything to the files beforehand:

https://www.mediafire.com/file/j1vkwar9a5w6ghj/exefs.zip/file

**Comment by masagrator** [comment]
Japanese release version is 1.0.2?

**Comment by Watkinsjo2** [comment]
Yeah, 1.0.2 is the version I have.

**Comment by masagrator** [comment]
[SenranKaguraPB-60FPS-JPN.zip](https://github.com/masagrator/NXGraphicsPatches/files/3896011/SenranKaguraPB-60FPS-JPN.zip)
Check if this is working.

**Comment by Watkinsjo2** [comment]
It's not working for me. I copied exefs_patches\SenranKaguraPB-60FPS-JPN\A0BD46B324ABDB68F346819492DDA7CE.ips to the atmosphere folder and am using sys-clk-editor with the suggested settings.

This is my first time applying an exefs patch, so was there something I needed to do prior to this?

**Comment by masagrator** [comment]
So there are 3 options:
* Your exefs dump is not from update, but from base game
* Sys-clk is not working
* You didn't restart Switch (it should not be necessary for newest Atmosphere)

**Comment by masagrator** [comment]
I checked and I was right - your exefs dump is not from update. I got it, so wait.

**Comment by masagrator** [comment]
[SenranKaguraPB-60FPS-JPNv2.zip](https://github.com/masagrator/NXGraphicsPatches/files/3896837/SenranKaguraPB-60FPS-JPNv2.zip)
Check now.

**Comment by Watkinsjo2** [comment]
It's working perfectly now. Sorry about giving you the wrong exefs -_- I thought I had to dump that one instead of the update.  I hope I didn't take up too much more of your time. Thank you again for helping me with everything!

**Comment by Attect** [comment]
It doesn't work for me. I have been try 3 zip files. 
01006CA00D454000
Ver. 1.0.2

**Comment by masagrator** [comment]
You have Chinese release. Send me exefs.

**Comment by Attect** [comment]
> You have Chinese/Korean release. Send me exefs.

https://drive.google.com/open?id=1zfQK_eFVm94oEaBhLqZUd_OaTZaUVZK5
I export exefs from game nsp and patch nsp,and I don't known whitch one is right.
I will delete it after you download it.

**Comment by masagrator** [comment]
[SenranKagura-60FPS-ChKo.zip](https://github.com/masagrator/NXGraphicsPatches/files/4476412/SenranKagura-60FPS-ChKo.zip)
To updated version. Test and share results.

**Comment by Attect** [comment]
> [SenranKagura-60FPS-ChKo.zip](https://github.com/masagrator/NXGraphicsPatches/files/4476412/SenranKagura-60FPS-ChKo.zip)
> To updated version. Test and share results.

Result:
It works in handheld mode, but it run slow in docked mode(...At the same time the game easier).

CPU:1785
GPU:921
MEM:1600
Docked video output: 1920*1080

**Comment by masagrator** [comment]
Well, this was expected.
