### ISSUE TITLE
Tales of Vesperia: Definitive Edition - 60fps outside of battle

### ISSUE THREAD

**Issue by iwubcode** [masagrator/NXGraphicsPatches#19]
**Full game title**
Tales of Vesperia: Definitive Edition

**Describe what you want to modify**
Change from 30fps to 60fps outside of battle

**Describe many informations about this topic**
PS4 and PC can hit 60fps everywhere, it'd be nice if the Switch version could do the same.

**Comment by masagrator** [comment]
Game is 60 FPS outside battle, it just has performance issues.
