### ISSUE TITLE
Yoshi's Crafted World Graphics Patch request

### ISSUE THREAD

**Issue by staringstar** [masagrator/NXGraphicsPatches#2]
**Full game title**
Yoshi's Crafted World

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.
Boost resolution for docke mode to 1600x900.
Change graphics settings to somethings better.
**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is using dynamic resolution. Can go as low as 360p.
Games resolution in handheld mode is 1280x720. Is using dynamic resolution. Can go as low as 576p.

Thanks in advance

**Comment by masagrator** [comment]
From what I see SwitchEngine.ini is responsible for dynamic resolution
`[/Script/Engine.RendererSettings]
r.DynamicResolution.Quality=1
r.DynamicResolution.MinTimeBudget=12.3
r.DynamicResolution.MaxTimeBudget=15.7
r.DynamicResolution.MinLevel=0
r.DynamicResolution.MaxLevel=2
r.DynamicResolution.Level0=100.0
r.DynamicResolution.Level1=90.0
r.DynamicResolution.Level2=80.0
r.DynamicResolution.TimeBlendRate=0.2`

According to this lowest handheld resolution should be 378p, not 360p.
But I couldn't find render resolution settings, only window resolution. 
I will not touch it as it can be done easily with my tutorial about making Unreal Engine 4 patches.
https://gbatemp.net/threads/how-to-unpack-and-repack-unreal-engine-4-files.531784/

I will try only to find predefined resolution.

**Comment by masagrator** [comment]
I don't know where you take those values for handheld mode, but it looks like they are wrong. Digital Foundry has pixel counted 880x495, which is above your 854x480 and probably it's not the highest resolution.

**Comment by staringstar** [comment]
I tried changing the resolution before but it just didnt work.

**Comment by staringstar** [comment]
here is the pak file with the edited values:
https://drive.google.com/open?id=13CbsFl2h6wjnrTKdHlNtjDoZALwYKEi-

**Comment by masagrator** [comment]
From what I checked you packed it wrongly. Game is using v4, you used v7 UnrealPak.
If it was crashing, then it was one of possible faults.
Code from exefs gives me that resolution in handheld mode is scaled with ini files. So digged and found it in
>/PJ033/Config/DefaultDeviceProfiles.ini

`[SwitchConsole DeviceProfile]` - docked mode
`[SwitchHandheld DeviceProfile]` - handheld mode
Main resolution is 1920x1080.
`+CVars=r.ScreenPercentage` - it scales resolution. 
`+CVars=r.ScreenPercentage=66` = 1280x720
`+CVars=r.ScreenPercentage=44.4` = 854x480 (so you had right, my bad)

I have changed ScreenPercentage for Console to 83.3, for Handheld to 66. Now you should get what you want.
https://github.com/masagrator/NXGraphicsPatches/tree/master/Yoshi's%20Crafted%20World/titles/01006000040C2000/romfs/PJ033/Content/Paks

**Comment by staringstar** [comment]
Thank you so much it worked really well. I guess my problem is that I used ue 4.21 to do the whole packing and unpacking.

**Comment by staringstar** [comment]
thanks it worked so well I guess Ill search for a way to install ue 4.19 do you know where I can download it.

**Comment by masagrator** [comment]
Epic Games Launcher -> you can find there any version.
