### ISSUE TITLE
Dragon's Dogma: Dark Arisen (010057E00AC56000)

### ISSUE THREAD

**Issue by anotherswitchanon** [masagrator/NXGraphicsPatches#21]
**Full game title**
Dragon's Dogma: Dark Arisen (010057E00AC56000)

**Describe what you want to modify**
60fps just like the US version.

**Describe many informations about this topic**
Should be the same as the US version.

**Additional context**
Just want this because the Japanese version is dual audio while the US version is american dub only.

**Comment by masagrator** [comment]
Done
https://gbatemp.net/threads/dragons-dogma-dark-arisen-60-fps-hack.553129/
