### ISSUE TITLE
Dragon Quest Builders 2

### ISSUE THREAD

**Issue by ToolerMaan** [masagrator/NXGraphicsPatches#25]
**Full game title**
Dragon Quest Builders 2

**Describe what you want to modify**
Would be really great to fix the Framerate of the game to *at least* run at constant 30fps (this is a problem in both docked and handheld mode). Not only that but to start up the game it takes around a minute.

**Describe many informations about this topic**
The FPS in the game can be all over the place. It's mostly at 30 but it can drop really hard for a couple seconds which is annoying.

**Additional context**
I recommend you check out this video: https://youtu.be/WQewHDQHCgU?t=335
It's a review from GameXplain where he shows DQB2's fps problems.

Thanks in advance!

**Comment by masagrator** [comment]
I can't help with optimization issues, so don't ask about speeding up loadings. I'm not a thaumaturge.

Havr you tried to check in handheld mode how it works with dock clocks?

**Comment by masagrator** [comment]
Because more than 30 days passed without response, I'm closing this issue.
