### ISSUE TITLE
Two game frame limit remove request

### ISSUE THREAD

**Issue by friedeinhard** [masagrator/NXGraphicsPatches#27]
'Fire Emblem Warriors'
quality mode frame limit remove

and

'pawarumi' frame limit remove

Can you do it?

**Comment by masagrator** [comment]
Fire Emblem Warriors Performance mode in docked is not 60 FPS handheld quality mode?

**Comment by friedeinhard** [comment]
YES docked and handheld same both 30 fps

**Comment by friedeinhard** [comment]
quality mode

**Comment by friedeinhard** [comment]
I want docked quality and performance mode same 60 fps

**Comment by masagrator** [comment]
But i'm docked mode 60 FPS quality mode will be unstable as f.
And if docked performance mode = handheld quality mode, but only difference is FPS, then there is not necessary to do this mod. I can't check it rn, do if you don't know, I will check it myself.

**Comment by friedeinhard** [comment]
unstable is not problem
I ready MAX CLOCK UP
Thanks answer.

**Comment by masagrator** [comment]
I mean unstable even with max clock up. I will check it when I can.

**Comment by friedeinhard** [comment]
Oh, I didn't know it was that bad. holy shxx...

**Comment by masagrator** [comment]
[Pawarumi60FPS.zip](https://github.com/masagrator/NXGraphicsPatches/files/4113377/Pawarumi60FPS.zip)
60 FPS for version 1.0.1

**Comment by masagrator** [comment]
And from what I checked for Fire Emblem there is no need for any additional patch. Quality Mode will be always in around 40 FPS after unlocking. 
So if you want 60 FPS, stick to Performance Mode.

**Comment by friedeinhard** [comment]
pawarumi patch is CORRECTLY working THANKS GRACIAS.
fire emblem warriors Quality MAXIMUM 40 fps??
so... 40fps is vanilla??
if so... OMG...
