### ISSUE TITLE
'Divinity original sin 2' remove fps cap??

### ISSUE THREAD

**Issue by friedeinhard** [masagrator/NXGraphicsPatches#29]
I'm sorry you're asking too much.
I want you to make sure you can do this.

**Comment by masagrator** [comment]
I have removed it for some version and it was working, but I couldn't test performance in long term. 
https://github.com/masagrator/NXGraphicsPatches/blob/experimental/Divinity%20Original%20Sin%20II/exefs_patches/Divinity2-60FPS/DBD602F66E2DE27D51F14BAECC16BD8F3605B197000000000000000000000000.ips
Main menu was struggling with going above 30 FPS, when gameplay in prologue was 60 FPS. I will try to make patch for 1.0.6 version and check if performance is improved.

**Comment by masagrator** [comment]
[Divinity60FPS-1.0.6.zip](https://github.com/masagrator/NXGraphicsPatches/files/4123586/Divinity60FPS-1.0.6.zip)
So it's only slightly better.
