### ISSUE TITLE
Crash Team Racing Nitro Fueled

### ISSUE THREAD

**Issue by CNemesis** [masagrator/NXGraphicsPatches#3]
**Full game title**
Crash Team Racing Nitro Fueled

**Describe what you want to modify**
Boost resolution for handheld mode to 854x720

**Describe many informations about this topic**
854x720 will give a stable FPS, native 720p gives slowdowns in handheld overlocked to 460mhz

**Additional context**

**Comment by masagrator** [comment]
How to set custom resolution you have here.
https://gbatemp.net/threads/crash-team-racing-720p-handheld-patch.541580/
