### ISSUE TITLE
Mega Man Zero/ZX Legacy Collection Undub and Uncensor

### ISSUE THREAD

**Issue by anotherswitchanon** [masagrator/NXGraphicsPatches#33]
**Full game title**
Mega Man Zero/ZX Legacy Collection

**Describe what you want to modify**
An exefs patch to undub and uncensor the english portion of the game as the game contains files for both japanese and english games.

**Describe many informations about this topic**
The Japanese version of Megaman Zero 1 to 4 has blood splatter when you kill enemies, this was censored in the english release.
Megaman ZX has Japanese voice acting but these were removed in the english release and replaced with silence, the cutscenes were dubbed but I don't know if the game has subtitles.
Megaman ZX Advent is dub only in the english release and needs an undub for both voices and cutscenes, I don't know if the game has subtitles.

**Additional context**
Just trying to minimize the amount of files needed in layeredfs since it would take a while to copy over and since the game has both japanese and english files, a exefs mod might be easier.

**Comment by masagrator** [comment]
This is repo for graphics patches, not content patches.
