### ISSUE TITLE
Hyrule Warriors Definitive Edition - 30FPS Lock Patch Request

### ISSUE THREAD

**Issue by mayongproton** [masagrator/NXGraphicsPatches#36]
**Full game title**
Hyrule Warriors Definitive Edition

**Describe what you want to modify**
Adjust in game 30 fps lock instead of upcap framerate

**Describe many informations about this topic**
This game using uncap framerate that unstable and has performance issues. It will be great if it lock 30 fps.

**Comment by staringstar** [comment]
Patch is here https://gbatemp.net/threads/request-hyrule-warriors-definitive-edition-30fps-lock-patch.559792/ .
