### ISSUE TITLE
Little Nightmares mod to lock at 30fps.

### ISSUE THREAD

**Issue by iOS4all** [masagrator/NXGraphicsPatches#39]
Little Nightmares

Hi @masagrator please can make a mod to make this game runs at locked 30 fps instead of 35 to 48. So it useless because it’s not at stable framerate.
This game is so much fun but because of unsteady framerate it makes the experience not that good. BTW It runs by unreal engine 4.
Thanks a lot and really appreciate.

**Comment by masagrator** [comment]
https://gbatemp.net/threads/a-mod-to-make-little-nightmares-runs-at-cap-30fps.563563/#post-9054258

**Comment by iOS4all** [comment]
Thanks a lot
