### ISSUE TITLE
Octopath 60 fps

### ISSUE THREAD

**Issue by Ness-666** [masagrator/NXGraphicsPatches#4]
**Full game title**
Octopath Traveler

**Describe what you want to modify**
Boost FPS to 60, if possible at

**Describe many informations about this topic**
Octopath on the switch runs at 30 fps, the pc release being in 60 .
I have seen a few videos with the mod but can not seem to find it

**Additional context**
https://clips.twitch.tv/FineDeadJayHumbleLife

**Comment by masagrator** [comment]
I was trying to make it working for quite some time. It's partially working because of some bugs, mostly some animations are double speed and when exploring companions have doubled textures when moving. I can upload it to the experimental branch if you want.

**Comment by Ness-666** [comment]
Sure that would be awesome! Thank you!

**Comment by masagrator** [comment]
[Octopath60-Alpha.zip](https://github.com/masagrator/NXGraphicsPatches/files/3488851/Octopath60-Alpha.zip)

**Comment by masagrator** [comment]
Patch is available for FPSLocker.
