### ISSUE TITLE
Gear Club Unlimited 2, 60fps mod

### ISSUE THREAD

**Issue by jnl327** [masagrator/NXGraphicsPatches#42]
**Full game title**
Gear Club Unlimited 2

**Describe what you want to modify**
60 fps in handeld mode.

**Describe many informations about this topic**
Game originally runs very slow in handheld mode, 30fps maximum. 

**Additional context**
If possible a resolution of 1280x720 would be great, but high fps numbers is more important to a racing game.

**Comment by masagrator** [comment]
Here you go. Issue is that performance is really bad.
1785/768/1600 average FPS is 40-50. It never gets to 60 from my tests.
It's only for 1.6.2

[GCU2-60FPS-1.6.2.zip](https://github.com/masagrator/NXGraphicsPatches/files/4638311/GCU2-60FPS-1.6.2.zip)

**Comment by jnl327** [comment]
Thank you very much for your effort!
