### ISSUE TITLE
Resident Evil 4 30fps cap

### ISSUE THREAD

**Issue by GaiaRevane** [masagrator/NXGraphicsPatches#43]
**Full game title**
Resident Evil 4

**Describe what you want to modify**
Cap the game at 30fps instead of 60.

**Describe many informations about this topic**
Enemy AI is known to glitch out at 60fps across all HD versions, and behaves as intended at 30fps. Other versions of the game include a 30fps toggle in the options, but Switch does not.

**Additional context**
None.

**Comment by masagrator** [comment]
[RE4-30FPS-1.0.1.zip](https://github.com/masagrator/NXGraphicsPatches/files/4785851/RE4-30FPS-1.0.1.zip)
Only for version 1.0.1
