### ISSUE TITLE
60FPS patch for XCDE

### ISSUE THREAD

**Issue by NikScepticeye** [masagrator/NXGraphicsPatches#46]
**Full game title**
Xenoblade Chronicles Definitive Edition

**Describe what you want to modify**
60fps patch on docked 720p and handheld 540p 
w/ max OC
**Describe many informations about this topic**
i just wanna see if it can run 60FPS

**Comment by masagrator** [comment]
https://gbatemp.net/threads/mod-xenoblade-chronicles-definitive-edition-60fps.567921/#post-9102373
