### ISSUE TITLE
Little nightmare

### ISSUE THREAD

**Issue by magi009** [masagrator/NXGraphicsPatches#47]
**Full game title**
Crash Bandicoot N.Sane Trilogy

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.

**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is not using dynamic resolution.

**Additional context**

**Comment by masagrator** [comment]
Next time check better what are you sending.

**Comment by magi009** [comment]
Omg, sorry sir.
