### ISSUE TITLE
SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated 

### ISSUE THREAD

**Issue by mat03111984** [masagrator/NXGraphicsPatches#48]
**Full game title**
SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated 

**Describe what you want to modify**
30 fps lock

**Describe many informations about this topic**
Game runs around 45-60 fps. .

**Additional context**

**Comment by masagrator** [comment]
New update locked game to 30 FPS.
