### ISSUE TITLE
Deadly Premonition 1 Origins - 30FPS cap lock

### ISSUE THREAD

**Issue by one-piece19** [masagrator/NXGraphicsPatches#49]
**Full game title**
Deadly Premonition Origins

**Describe what you want to modify**
Add a 30 FPS cap lock.

**Describe many informations about this topic** The OG Xbox 360 release was 30 FPS. This port framerate is ranging from 30-45 fps with very inconsistent jumpings. I think this game can be more enjoyable by locking the framerate to 30Fps.

*As a note: this is NOT for the second game, that game runs at 9-20 fps, wich is a lost cause. 

**Additional context**
Frame rate video analysis
https://youtu.be/lvteufsqpig

**Comment by lastisin** [comment]
I agree. It would be much stable gameplay than how it is for now.

**Comment by masagrator** [comment]
Game is not using at all any setpresentinterval function, so making IPS patch without finding config file is out of question.
Game is 32-bit, so no plugins possible to make.

atm is a lost cause for me.
