### ISSUE TITLE
Game patch request for Kirby Star Allies

### ISSUE THREAD

**Issue by JonJaded** [masagrator/NXGraphicsPatches#5]
Kirby Star Allies

Boost frame rate for docked mode (or handheld too if possible) to 60 FPS in gameplay, instead of only in menus.

Framerate fluxuates between 30 and 60 fps. 60 FPS in menus, and 30 in game.  dynamic resolution is used, targets 720p in handheld, (but usually runs under that) and 1536x864 in docked. 

Whenever you get the chance, thank you! (Also good luck.)

**Comment by masagrator** [comment]
I can finally say that thanks to many people we achieved in unlocking 60 FPS in Kirby Star Allies in form of cheat. We will release it soon.
