### ISSUE TITLE
NBA 2K 20

### ISSUE THREAD

**Issue by okhal95** [masagrator/NXGraphicsPatches#52]
**Full game title**
NBA 2K 20
**Describe what you want to modify**
60 FPS in handheld or docked mode.

**Describe many informations about this topic**
Unfortunately I couldn't find any details online about the game resolution. But the game runs at 30 fps bot in handheld and docked mode. 

**Additional context**
It's my first time submitting a request here so I don't know which files to join. Sorry.

**Comment by masagrator** [comment]
https://github.com/masagrator/NXGraphicsPatches/issues/37
