### ISSUE TITLE
Spyro Reignited Trilogy - 60FPS Mod Switch.

### ISSUE THREAD

**Issue by SoulDDragon** [masagrator/NXGraphicsPatches#55]
**Full game title**
Spyro Reignited Trilogy.

**Describe what you want to modify**
The framerate from 30fps to 60fps.

**Describe many informations about this topic**
Switch in docked mode uses a dynamic resolution with the lowest resolution found being 960x540 and the highest resolution found being 1280x720. Switch in handheld mode uses a dynamic resolution with the lowest resolution found being 768x432 and the highest resolution found being 1152x648. The game is locked at 30fps in both handheld mode and dock mode.

**Comment by masagrator** [comment]
Use FPSLocker
