### ISSUE TITLE
DRAGON QUEST XI S: Echoes of an Elusive Age – Definitive Edition

### ISSUE THREAD

**Issue by iOS4all** [masagrator/NXGraphicsPatches#59]
**Full game title**
DRAGON QUEST XI S: Echoes of an Elusive Age – Definitive Edition

**Describe what you want to modify**
Makes this game capped at 30fps instead of unstable framerate.

Thanks a lot.

**Comment by masagrator** [comment]
This game is capped at 30. Use OC if performance doesn't satisfy you.
