### ISSUE TITLE
Dark Souls Remastered - 60 FPS

### ISSUE THREAD

**Issue by timstoneberg** [masagrator/NXGraphicsPatches#6]
**Full game name
Dark Souls Remastered

**Describe what you want to modify**
Increase frame rate to 60

**Comment by masagrator** [comment]
Today I have managed to unlock 60 FPS with correct speed. It needs more testing for possible glitches to check what is the jest way to share mod, so wait patiently. :)

**Comment by masagrator** [comment]
Done
https://gbatemp.net/threads/darksiders-2-60-fps-mod.555117/
