### ISSUE TITLE
Super Mario 3D World + Bowser's Fury

### ISSUE THREAD

**Issue by Justyn83** [masagrator/NXGraphicsPatches#65]
**Full game title**
Super Mario 3D World + Bowser's Fury

**Describe what you want to modify**
Bowser's Fury: Boost resolution for undocked mode to 1080p and/or 60fps

**Describe many informations about this topic**
Games resolution in docked mode is 720p to 1080p

**Additional context**
Super Mario 3D World is 720p to 1080p 60Hz in docked and 720p in undocked mode.
Bowsers Fury is 720p to 1080p 60fps in docked mode and 720p/30fps in undocked mode.

**Comment by masagrator** [comment]
Use ReverseNX and OC.

**Comment by Craftyawesome** [comment]
Is it possible to allow the dynamic resolution to go below 720p? 768MHz isn't fully stable 60 fps, and 460MHz is super slow.
