### ISSUE TITLE
Ni no Kuni II: Revenant Kingdom Lock 30 fps

### ISSUE THREAD

**Issue by keishatheprettiest** [masagrator/NXGraphicsPatches#71]
**Full game title**
Ni no Kuni II: Revenant Kingdom

**Describe what you want to modify**
Lock fps to 30 fps

**Describe many informations about this topic**
Framerate is uncapped so it's quite uncomfortable to play with an uncapped framerate

**Comment by masagrator** [comment]
Use FPSLocker.
