### ISSUE TITLE
Link in Dark souls

### ISSUE THREAD

**Issue by broccolifro** [masagrator/NXGraphicsPatches#75]
**Full game title**
Dark souls (switch)

**Describe what you want to modify**
Link to be a playable character

**Describe many informations about this topic**
i'd like this mod to be converted to be able to play on atmosphere

**Additional context**
link to the mod: https://www.nexusmods.com/darksoulsremastered/mods/89?tab=description

**Comment by masagrator** [comment]
This is graphics patches repo, not swapping models repo

**Comment by broccolifro** [comment]
oh alright thank you for checking this out! @masagrator  :)
