### ISSUE TITLE
Slime rancher 60fps patch request

### ISSUE THREAD

**Issue by Jujube54** [masagrator/NXGraphicsPatches#76]
**Full game title**

Slime Rancher: Plortable Edition

**Describe what you want to modify**
Boost framerate limit to 60fps

**Describe many informations about this topic**
Games framerate limit is 30 fps.

**Additional context**
Not expecting it to work at stable 60fps even if overclocked, but worth the try I think.
![F1D5B3A1-3F1F-4744-8418-1AE0D1EDF266](https://user-images.githubusercontent.com/109028351/200184586-468353a1-6a3e-4ae5-a9ca-b681580a92b7.jpeg)

**Comment by masagrator** [comment]
It's already unlocked 60 FPS.
