### ISSUE TITLE
resident

### ISSUE THREAD

**Issue by Master-Icarus** [masagrator/NXGraphicsPatches#77]
**Full game title**
Crash Bandicoot N.Sane Trilogy

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.

**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is not using dynamic resolution.

**Additional context**

**Comment by masagrator** [comment]
You didn't even wrote full game's name. Not mentioning that you leaved template at default state.

**Comment by masagrator** [comment]
Since I got no reply I'm closing the issue.

**Comment by theboy181** [comment]
rude! ;)
