### ISSUE TITLE
gear club unlimited 2

### ISSUE THREAD

**Issue by Artur050207** [masagrator/NXGraphicsPatches#78]
**Full game title**
Crash Bandicoot N.Sane Trilogy

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.

**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is not using dynamic resolution.

**Additional context**

**Comment by masagrator** [comment]
Since you didn't even spend 1 minute on explaining what you want, I will assume you want 60 FPS and I'm closing this as duplicate.

https://github.com/masagrator/NXGraphicsPatches/issues/42
