### ISSUE TITLE
Gear Club 2 Unlimited - Graphics Mod 60 FPS

### ISSUE THREAD

**Issue by Pieszczoch1234** [masagrator/NXGraphicsPatches#80]
**Full game title**
Gear Club 2 Unlimited

**Describe what you want to modify**
Boost FPS to 60 and maybe graphics?

**Describe many informations about this topic**
Game work in choppy 30 fps, in 60 it could be diffrent game. Maybe also the graphics can be bumped up a bit, the shading looks very poor compared to versions for other platforms.

**Comment by masagrator** [comment]
60 FPS patch is available for FPSLocker.
