### ISSUE TITLE
gear club unlimited 2 60fps mod

### ISSUE THREAD

**Issue by caboloso42** [masagrator/NXGraphicsPatches#82]
**Full game title**
Crash Bandicoot N.Sane Trilogy

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.

**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is not using dynamic resolution.

**Additional context**

**Comment by masagrator** [comment]
It's available in FPSLocker.
