### ISSUE TITLE
RE5 titleid: 010018100CD46000

### ISSUE THREAD

**Issue by Marioley** [masagrator/NXGraphicsPatches#92]
**Full game title**
Crash Bandicoot N.Sane Trilogy

**Describe what you want to modify**
Boost resolution for handheld mode to 1280x720.

**Describe many informations about this topic**
Games resolution in handheld mode is 854x480. Is not using dynamic resolution.

**Additional context**

**Comment by masagrator** [comment]
Try harder next time.
